/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 src/assets/models/small-village/lamp-old-street.glb -o src/pages/SmallVillage/LampOldModel.tsx -t s 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube12776: THREE.Mesh
    Cube12776_1: THREE.Mesh
    Cube12776_2: THREE.Mesh
    Cube12776_3: THREE.Mesh
  }
  materials: {
    roof: THREE.MeshStandardMaterial
    ['Material.028']: THREE.MeshStandardMaterial
    ['Material.029']: THREE.MeshStandardMaterial
    ['Material.032']: THREE.MeshStandardMaterial
  }
}

// type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function LampOldModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('src/assets/models/small-village/lamp-old-street.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube12776.geometry} material={materials.roof} />
      <mesh geometry={nodes.Cube12776_1.geometry} material={materials['Material.028']} />
      <mesh geometry={nodes.Cube12776_2.geometry} material={materials['Material.029']} />
      <mesh geometry={nodes.Cube12776_3.geometry} material={materials['Material.032']} />
    </group>
  )
}

useGLTF.preload('src/assets/models/small-village/lamp-old-street.glb')
